There are different types of probability distributions, including normal distribution, binomial distribution, multinomial distribution and Bernoulli distribution.

weight initialization

In [1]:
import torch

torch.manual_seed(1234)

In [2]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In a continuous uniform distribution, each number has an equal chance of being selected.

In [5]:
torch.Tensor(4,4).uniform_(0,1)

tensor([[0.8839, 0.8083, 0.7528, 0.8988],
        [0.6839, 0.7658, 0.9149, 0.3993],
        [0.1100, 0.2541, 0.4333, 0.4451],
        [0.4966, 0.7865, 0.6604, 0.1303]])

In statistics, the Bernoulli distribution is considered as the discrete probability distribution, which has two possible outcomes. If the event happens, then the value is 1, and if the event does not happen, then the value is 0.

In [16]:
torch.bernoulli(torch.Tensor(4,4).uniform_(0,1))

tensor([[1., 1., 1., 1.],
        [0., 0., 1., 1.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.]])

In [29]:
torch.Tensor([10,23,40,12,326,125,87,32,87,2,6,])
torch.multinomial(torch.tensor([10,23,40,12,326,125,87,32,87,2,6]).type(torch.DoubleTensor), 5)

tensor([2, 1, 5, 4, 3])

.....and returns tensor's index value

In [34]:
torch.normal(mean=torch.arange(1.,11.), std=torch.arange(1,0,-0.1))

tensor([ 1.6593,  1.9179,  2.8028,  4.5697,  4.9009,  5.8350,  6.1068,  7.8885,
         8.7117, 10.1447])

In [35]:
torch.normal(mean=0.5, std=torch.arange(1.,6.))

tensor([-0.8189,  2.5637,  1.8899,  3.5019, -3.5511])

In [36]:
torch.normal(mean=0.5,std=torch.arange(0.2,0.6))

tensor([0.3978])

In [44]:
torch.arange(0.2,1.6)

tensor([0.2000, 1.2000])

In [45]:
from torch.autograd import Variable

In [46]:
Variable(torch.ones(2,2),requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [47]:
a, b = 12, 23
x1 = Variable(torch.randn(a, b), requires_grad=True)
x2 = Variable(torch.randn(a, b), requires_grad=True)
x3 = Variable(torch.randn(a, b), requires_grad=True)

In [49]:
c = x1 * x2
d = a + x3
e =  torch.sum(d)

e.backward()

print(e)

tensor(3328.3894, grad_fn=<SumBackward0>)
