There are different types of probability distributions, including normal distribution, binomial distribution, multinomial distribution and Bernoulli distribution.

weight initialization

In [16]:
import torch

torch.manual_seed(1234)

In [17]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In a continuous uniform distribution, each number has an equal chance of being selected.

In [18]:
torch.Tensor(4,4).uniform_(0,1)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In statistics, the Bernoulli distribution is considered as the discrete probability distribution, which has two possible outcomes. If the event happens, then the value is 1, and if the event does not happen, then the value is 0.

In [19]:
torch.bernoulli(torch.Tensor(4,4).uniform_(0,1))

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])

In [20]:
torch.Tensor([10,23,40,12,326,125,87,32,87,2,6,])
torch.multinomial(torch.tensor([10,23,40,12,326,125,87,32,87,2,6]).type(torch.DoubleTensor), 5)

tensor([4, 5, 8, 6, 2])

.....and returns tensor's index value

In [21]:
torch.normal(mean=torch.arange(1.,11.), std=torch.arange(1,0,-0.1))

tensor([1.9847, 3.3247, 3.2480, 5.1080, 5.1411, 5.7281, 7.2094, 8.0814, 8.9344,
        9.9932])

In [22]:
torch.normal(mean=0.5, std=torch.arange(1.,6.))

tensor([ 1.2300, -1.4367,  9.8666,  2.6935,  1.9372])

In [23]:
torch.normal(mean=0.5,std=torch.arange(0.2,0.6))

tensor([0.2254])

In [24]:
torch.arange(0.2,1.6)

tensor([0.2000, 1.2000])

In [25]:
from torch.autograd import Variable

In [26]:
Variable(torch.ones(2,2),requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [27]:
a, b = 12, 23
x1 = Variable(torch.randn(a, b), requires_grad=True)
x2 = Variable(torch.randn(a, b), requires_grad=True)
x3 = Variable(torch.randn(a, b), requires_grad=True)

In [28]:
c = x1 * x2
d = a + x3
e =  torch.sum(d)

e.backward()

print(e)

tensor(3287.6458, grad_fn=<SumBackward0>)


create basic statistics(partially with gpu accelerations)

In [30]:
torch.mean(torch.tensor([10,120,123,5,3,5,457,34,56,45,536,82,70,6]).type(torch.DoubleTensor))

tensor(110.8571, dtype=torch.float64)

In [31]:
d = torch.randn(4,5)

In [32]:
torch.mean(d,dim=0)

tensor([-0.0485,  0.5087, -0.2849,  0.5082,  1.1420])

In [33]:
torch.mean(d,dim=1)

tensor([ 1.0723,  0.2804, -0.2885,  0.3961])

In [34]:
torch.median(d,dim=0)

torch.return_types.median(
values=tensor([ 0.0030, -0.5807, -0.6911,  0.5924,  1.0300]),
indices=tensor([2, 1, 1, 0, 2]))

In [35]:
torch.median(d,dim=1)

torch.return_types.median(
values=tensor([ 0.7223, -0.5807, -0.3527,  0.3602]),
indices=tensor([2, 1, 3, 0]))

In [36]:
torch.mode(d)

torch.return_types.mode(
values=tensor([ 0.2778, -0.8351, -1.1132, -0.9132]),
indices=tensor([0, 0, 1, 4]))

In [37]:
torch.mode(d,dim=1)

torch.return_types.mode(
values=tensor([ 0.2778, -0.8351, -1.1132, -0.9132]),
indices=tensor([0, 0, 1, 4]))

In [38]:
torch.mode(d,dim=0)

torch.return_types.mode(
values=tensor([-0.8351, -1.1132, -1.0094, -0.3527, -0.9132]),
indices=tensor([1, 2, 2, 2, 3]))

In [39]:
torch.std(d)

tensor(1.0971)

In [40]:
torch.std(d,dim=0)

tensor([0.5462, 1.5814, 0.7571, 0.6017, 1.4958])

In [41]:
torch.std(d,dim=1)

tensor([0.7614, 1.4425, 0.8700, 1.0632])

In [42]:
torch.var(d)

tensor(1.2036)

gradient computation

In [43]:
def forward(x):
    return x * w

In [79]:
import torch
from torch.autograd import Variable

x_data = [11. , 22. , 33.,44,55,66,77,88]
y_data = [11. , 22. , 33.,44,55,66,77,88]

w = Variable(torch.Tensor([1.0]), requires_grad = True)

print("predict before training", 4, forward(4).data[0])

predict before training 4 tensor(4.)


In [80]:
def loss(x,y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

In [81]:
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ",x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data

        # set gradient to zero after update w.data
        w.grad.data.zero_()

    print("progress: ", epoch, l.data[0])

	grad:  11.0 11.0 tensor(0.)
	grad:  22.0 22.0 tensor(0.)
	grad:  33.0 33.0 tensor(0.)
	grad:  44 44 tensor(0.)
	grad:  55 55 tensor(0.)
	grad:  66 66 tensor(0.)
	grad:  77 77 tensor(0.)
	grad:  88 88 tensor(0.)
progress:  0 tensor(0.)
	grad:  11.0 11.0 tensor(0.)
	grad:  22.0 22.0 tensor(0.)
	grad:  33.0 33.0 tensor(0.)
	grad:  44 44 tensor(0.)
	grad:  55 55 tensor(0.)
	grad:  66 66 tensor(0.)
	grad:  77 77 tensor(0.)
	grad:  88 88 tensor(0.)
progress:  1 tensor(0.)
	grad:  11.0 11.0 tensor(0.)
	grad:  22.0 22.0 tensor(0.)
	grad:  33.0 33.0 tensor(0.)
	grad:  44 44 tensor(0.)
	grad:  55 55 tensor(0.)
	grad:  66 66 tensor(0.)
	grad:  77 77 tensor(0.)
	grad:  88 88 tensor(0.)
progress:  2 tensor(0.)
	grad:  11.0 11.0 tensor(0.)
	grad:  22.0 22.0 tensor(0.)
	grad:  33.0 33.0 tensor(0.)
	grad:  44 44 tensor(0.)
	grad:  55 55 tensor(0.)
	grad:  66 66 tensor(0.)
	grad:  77 77 tensor(0.)
	grad:  88 88 tensor(0.)
progress:  3 tensor(0.)
	grad:  11.0 11.0 tensor(0.)
	grad:  22.0 22.0 tensor(0.

In [82]:
print("predict after: ", 4, forward(4).data[0])

predict after:  4 tensor(4.)


In [78]:
from torch import FloatTensor
from torch.autograd import Variable

a = Variable(FloatTensor([5]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (12,53,91,73)]

w1,w2,w3,w4  = weights

b = w1*a
c = w2*a
d = w3*b + w4*c
Loss = (10-d)

Loss.backward()

for index, weights in enumerate(weights, start = 1):
    gradient, *_ = weights.grad.data 
    print(f"Gradient of w{index} w.r.t to Loss: {gradient}")

Gradient of w1 w.r.t to Loss: -455.0
Gradient of w2 w.r.t to Loss: -365.0
Gradient of w3 w.r.t to Loss: -60.0
Gradient of w4 w.r.t to Loss: -265.0


Matrix operations

In [83]:
x = Variable(torch.Tensor(4,4).uniform_(-4,5))
y = Variable(torch.Tensor(4,4).uniform_(-3,2))

z = torch.mm(x,y)
print(z.size())

torch.Size([4, 4])


In [84]:
z = Variable(torch.Tensor(4,4).uniform_(-5,5))
z

tensor([[-3.3983,  1.7528,  0.5627,  4.9053],
        [ 3.8294, -4.6452,  4.2984,  4.5839],
        [ 2.6059, -0.2551,  4.8466,  0.3225],
        [ 0.2922, -0.2340,  2.6930, -0.4334]])

In [85]:
print(f'requires gradient: {z.requires_grad}')
print(f'Volatile: {z.volatile}')
print(f'gradient: {z.grad}')
print(z.data)

requires gradient: False
Volatile: False
gradient: None
tensor([[-3.3983,  1.7528,  0.5627,  4.9053],
        [ 3.8294, -4.6452,  4.2984,  4.5839],
        [ 2.6059, -0.2551,  4.8466,  0.3225],
        [ 0.2922, -0.2340,  2.6930, -0.4334]])


C:\Users\Administrator\AppData\Local\Temp\ipykernel_9920\897670538.py:2: UserWarning: volatile was removed (Variable.volatile is always False)
  print(f'Volatile: {z.volatile}')


tensor operations. dimension of a matrix and a vector or scalar should be compatible.

In [87]:

mat1 = torch.FloatTensor(4,4).uniform_(0,1)
mat1

tensor([[0.1947, 0.2268, 0.9587, 0.2615],
        [0.7256, 0.7673, 0.5667, 0.1863],
        [0.4642, 0.4016, 0.9981, 0.8452],
        [0.5569, 0.7666, 0.1084, 0.7874]])

In [88]:

mat2 = torch.FloatTensor(5,4).uniform_(0,1)
mat2

tensor([[0.7348, 0.9939, 0.3580, 0.1682],
        [0.9159, 0.9878, 0.5393, 0.6097],
        [0.9861, 0.0763, 0.3469, 0.1317],
        [0.7387, 0.8339, 0.0693, 0.4194],
        [0.0466, 0.8690, 0.8990, 0.6630]])

In [89]:
vec1 = torch.FloatTensor(4).uniform_(0,1)

In [90]:
mat1+0.5

tensor([[0.6947, 0.7268, 1.4587, 0.7615],
        [1.2256, 1.2673, 1.0667, 0.6863],
        [0.9642, 0.9016, 1.4981, 1.3452],
        [1.0569, 1.2666, 0.6084, 1.2874]])

In [91]:
mat2-10

tensor([[-9.2652, -9.0061, -9.6420, -9.8318],
        [-9.0841, -9.0122, -9.4607, -9.3903],
        [-9.0139, -9.9237, -9.6531, -9.8683],
        [-9.2613, -9.1661, -9.9307, -9.5806],
        [-9.9534, -9.1310, -9.1010, -9.3370]])

In [92]:
vec1

tensor([0.4962, 0.4947, 0.8344, 0.6721])

In [93]:
mat2+vec1

tensor([[1.2309, 1.4886, 1.1925, 0.8403],
        [1.4121, 1.4825, 1.3737, 1.2819],
        [1.4822, 0.5709, 1.1813, 0.8039],
        [1.2349, 1.3286, 0.9038, 1.0915],
        [0.5428, 1.3636, 1.7334, 1.3352]])

In [96]:
mat2*mat1

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 0

In [98]:
torch.mm(mat2, mat1)

tensor([[1.1241, 1.2020, 1.6433, 0.8123],
        [1.4850, 1.6498, 2.0423, 1.3595],
        [0.4817, 0.5225, 1.3492, 0.6690],
        [1.0147, 1.1568, 1.2955, 0.7374],
        [1.4261, 1.5467, 1.5063, 1.4559]])

we are going to use the most commonly used statistical distributions, their arguments in senarios of problems.

the Bernoulli distribution is the special case of binomial distribution, in which the number of trials can be more than one.

but in bernoulli distribution, the number of experiment or trials remains one.

In [99]:
from torch.distributions.bernoulli import Bernoulli

dist = Bernoulli(torch.tensor([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]))

In [113]:
dist.sample()

tensor([0., 1., 1., 0., 0., 0., 1., 0., 1.])

beta distribution:


In [114]:
from torch.distributions.beta import Beta
dist = Beta(torch.tensor([0.5]), torch.tensor([0.5]))
dist

Beta()

In [116]:
dist.sample()

tensor([0.2031])

In [119]:
from torch.distributions.binomial import Binomial
dist = Binomial(100, torch.tensor([0,0.2,0.8,1]))
dist.sample()

tensor([  0.,  15.,  89., 100.])

In [133]:
from torch.distributions.categorical import Categorical

dist = Categorical(torch.tensor([0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2]))
dist

Categorical(probs: torch.Size([10]))

In [138]:
dist.sample()

tensor(5)

In [143]:
from torch.distributions.laplace import Laplace
dist = Laplace(torch.tensor([10.0]), torch.tensor([0.990]))
dist.sample()

tensor([9.7408])

In [145]:
from torch.distributions.normal import Normal
dist = Normal(torch.tensor([100.0]), torch.tensor([10.0]))

dist.sample()

tensor([101.3155])