In [20]:
import torch

y = torch.randn(1,2,3,4,5)

In [21]:
assert(torch.is_tensor(y))

In [22]:
assert(not torch.is_storage(y))

In [23]:
print(torch.numel(y))

120


In [24]:
print(y)

tensor([[[[[-0.3844,  1.6452,  0.2411,  0.8813, -3.9334],
           [-0.1088, -0.2413, -2.0714, -0.4838,  0.9344],
           [ 1.2391, -2.3255, -0.5204, -0.5000,  0.1336],
           [-0.1430,  0.1191,  0.8325,  0.8536, -0.1060]],

          [[-0.3402,  0.1573,  2.0214, -1.4418, -0.6133],
           [ 0.7442, -0.1030, -0.1192,  0.8370, -0.7131],
           [-1.3718,  0.3658, -2.0196, -0.0527,  1.7032],
           [-2.4950, -0.5343,  0.3110, -0.0647,  1.4591]],

          [[-1.6840,  0.7531, -0.0335,  2.1366,  0.6497],
           [ 0.2644,  1.0670, -0.6893,  0.7579,  0.3606],
           [ 0.5217, -1.3710,  0.1513,  2.1667, -0.3174],
           [ 1.1552, -0.0937, -0.8619, -0.2699,  0.7279]]],


         [[[ 0.0299,  0.1891, -0.4900,  0.7757, -0.5384],
           [-1.2646, -1.3479,  0.9535,  0.3745, -1.3010],
           [-0.2151, -0.6806,  1.0854, -1.2240, -0.8809],
           [-1.1643, -1.2585, -0.2879,  0.0185,  1.2190]],

          [[ 0.9874,  0.3270,  0.8481, -0.4816,  0.9104],
    

In [25]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
torch.numel(torch.zeros(4,4))

16

In [27]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [28]:
torch.eye(4,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [29]:
import numpy as np
y1 = np.array(y)

In [30]:
y1

array([[[[[-0.38436955,  1.645234  ,  0.2410805 ,  0.88128924,
           -3.9333868 ],
          [-0.10884347, -0.2412626 , -2.0713708 , -0.48380375,
            0.9344038 ],
          [ 1.2391218 , -2.32552   , -0.5203861 , -0.5000376 ,
            0.13356239],
          [-0.14296795,  0.11905625,  0.8325026 ,  0.8536404 ,
           -0.10603266]],

         [[-0.3401557 ,  0.15734148,  2.0214345 , -1.441779  ,
           -0.6133114 ],
          [ 0.74423546, -0.10296459, -0.11915824,  0.8369684 ,
           -0.7130541 ],
          [-1.3718362 ,  0.36578277, -2.0195832 , -0.05274539,
            1.7032485 ],
          [-2.4950163 , -0.5343319 ,  0.3110292 , -0.06474748,
            1.4591235 ]],

         [[-1.6839694 ,  0.753084  , -0.03346388,  2.136644  ,
            0.64971715],
          [ 0.26438367,  1.0670043 , -0.68928254,  0.7579049 ,
            0.36056983],
          [ 0.5216868 , -1.3709745 ,  0.15132241,  2.1666567 ,
           -0.31738645],
          [ 1.1552271 , -0.0

In [31]:
torch.from_numpy(y1)

tensor([[[[[-0.3844,  1.6452,  0.2411,  0.8813, -3.9334],
           [-0.1088, -0.2413, -2.0714, -0.4838,  0.9344],
           [ 1.2391, -2.3255, -0.5204, -0.5000,  0.1336],
           [-0.1430,  0.1191,  0.8325,  0.8536, -0.1060]],

          [[-0.3402,  0.1573,  2.0214, -1.4418, -0.6133],
           [ 0.7442, -0.1030, -0.1192,  0.8370, -0.7131],
           [-1.3718,  0.3658, -2.0196, -0.0527,  1.7032],
           [-2.4950, -0.5343,  0.3110, -0.0647,  1.4591]],

          [[-1.6840,  0.7531, -0.0335,  2.1366,  0.6497],
           [ 0.2644,  1.0670, -0.6893,  0.7579,  0.3606],
           [ 0.5217, -1.3710,  0.1513,  2.1667, -0.3174],
           [ 1.1552, -0.0937, -0.8619, -0.2699,  0.7279]]],


         [[[ 0.0299,  0.1891, -0.4900,  0.7757, -0.5384],
           [-1.2646, -1.3479,  0.9535,  0.3745, -1.3010],
           [-0.2151, -0.6806,  1.0854, -1.2240, -0.8809],
           [-1.1643, -1.2585, -0.2879,  0.0185,  1.2190]],

          [[ 0.9874,  0.3270,  0.8481, -0.4816,  0.9104],
    

In [32]:
torch.linspace(2,10, steps=25)

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [33]:
torch.logspace(start=-10, end=10,steps=15)

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1969e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

In [34]:
torch.rand(10)

tensor([0.8961, 0.3223, 0.1449, 0.9818, 0.6321, 0.9429, 0.3904, 0.3355, 0.6562,
        0.5363])

In [35]:
torch.rand(4,5)

tensor([[0.7870, 0.6531, 0.8814, 0.7327, 0.7986],
        [0.0307, 0.4319, 0.3651, 0.4040, 0.0350],
        [0.3728, 0.0559, 0.4866, 0.3741, 0.9453],
        [0.8545, 0.7525, 0.6163, 0.8299, 0.1881]])

In [36]:
torch.randperm(10)

tensor([3, 4, 1, 6, 9, 8, 2, 7, 5, 0])

In [37]:
torch.arange(10,40,2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [38]:
torch.arange(10,20)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
d = torch.randn(4,5)

In [40]:
torch.argmin(d)

tensor(0)

In [41]:
torch.argmin(d, dim=0)

tensor([0, 3, 1, 1, 0])

In [42]:
torch.argmin(d, dim=1)

tensor([0, 3, 3, 3])

In [43]:
torch.argmax(d, dim=1)

tensor([2, 0, 4, 2])

In [44]:
x = torch.randn(4,5)

In [45]:
torch.cat((x,x))

tensor([[ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384],
        [ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384]])

In [46]:
torch.cat((x,x),0)

tensor([[ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384],
        [ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384]])

In [47]:
torch.cat((x,x),1)

tensor([[ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440,  0.3947, -0.4170,  1.3281,
         -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545,  1.7530, -0.1202, -0.0493,
         -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036, -0.7313,  0.2281, -0.5024,
         -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384, -0.0382,  0.7306,  0.8513,
          1.1914,  2.1384]])

In [48]:
a = torch.randn(4,4)
print(a)
torch.chunk(a,2)

tensor([[ 1.1466,  2.2229, -2.3152,  0.2896],
        [ 3.0416,  2.3078,  1.0196, -1.0720],
        [ 0.2858,  0.1514, -0.3718,  1.2415],
        [-1.0209, -0.6524,  1.1536,  1.2637]])


(tensor([[ 1.1466,  2.2229, -2.3152,  0.2896],
         [ 3.0416,  2.3078,  1.0196, -1.0720]]),
 tensor([[ 0.2858,  0.1514, -0.3718,  1.2415],
         [-1.0209, -0.6524,  1.1536,  1.2637]]))

In [50]:
torch.chunk(a,2,1)

(tensor([[ 1.1466,  2.2229],
         [ 3.0416,  2.3078],
         [ 0.2858,  0.1514],
         [-1.0209, -0.6524]]),
 tensor([[-2.3152,  0.2896],
         [ 1.0196, -1.0720],
         [-0.3718,  1.2415],
         [ 1.1536,  1.2637]]))

In [51]:
torch.Tensor([[11,22],[23,13]])

tensor([[11., 22.],
        [23., 13.]])

In [64]:
torch.gather(torch.Tensor([[11,22],[23,13]]),0,torch.LongTensor([[1,1],[1,0]]))

tensor([[23., 13.],
        [23., 22.]])

In [65]:
a = torch.randn(4,4)

In [66]:
indices = torch.LongTensor([0,2])

In [67]:
print(a)

tensor([[-0.0157, -0.6910,  0.1733,  1.1875],
        [ 0.3440, -0.1073,  0.0034, -0.1263],
        [ 0.0072, -0.8896,  0.0521,  0.0128],
        [ 1.0221, -0.0056,  0.5239,  1.9186]])


In [68]:
torch.index_select(a,0,indices)

tensor([[-0.0157, -0.6910,  0.1733,  1.1875],
        [ 0.0072, -0.8896,  0.0521,  0.0128]])

In [69]:
torch.index_select(a,1,indices)

tensor([[-0.0157,  0.1733],
        [ 0.3440,  0.0034],
        [ 0.0072,  0.0521],
        [ 1.0221,  0.5239]])

In [70]:
torch.nonzero(torch.tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [71]:
torch.split(torch.tensor([12,21,23,23,4,6,213]),2)

(tensor([12, 21]), tensor([23, 23]), tensor([4, 6]), tensor([213]))

In [72]:
torch.split(torch.tensor([123,124,365,23,457,1,4,235]),3)

(tensor([123, 124, 365]), tensor([ 23, 457,   1]), tensor([  4, 235]))

In [73]:
x

tensor([[ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384]])

In [74]:
x.t()

tensor([[ 0.3947,  1.7530, -0.7313, -0.0382],
        [-0.4170, -0.1202,  0.2281,  0.7306],
        [ 1.3281, -0.0493, -0.5024,  0.8513],
        [-0.0438, -0.7183, -1.8715,  1.1914],
        [ 0.3440, -1.9545, -0.2036,  2.1384]])

In [75]:
x.transpose(1,0)

tensor([[ 0.3947,  1.7530, -0.7313, -0.0382],
        [-0.4170, -0.1202,  0.2281,  0.7306],
        [ 1.3281, -0.0493, -0.5024,  0.8513],
        [-0.0438, -0.7183, -1.8715,  1.1914],
        [ 0.3440, -1.9545, -0.2036,  2.1384]])

In [76]:
x

tensor([[ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384]])

In [77]:
torch.unbind(x,1)

(tensor([ 0.3947,  1.7530, -0.7313, -0.0382]),
 tensor([-0.4170, -0.1202,  0.2281,  0.7306]),
 tensor([ 1.3281, -0.0493, -0.5024,  0.8513]),
 tensor([-0.0438, -0.7183, -1.8715,  1.1914]),
 tensor([ 0.3440, -1.9545, -0.2036,  2.1384]))

In [78]:
torch.unbind(x)

(tensor([ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440]),
 tensor([ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545]),
 tensor([-0.7313,  0.2281, -0.5024, -1.8715, -0.2036]),
 tensor([-0.0382,  0.7306,  0.8513,  1.1914,  2.1384]))

In [80]:
torch.unbind(x.transpose(1,0))

(tensor([ 0.3947,  1.7530, -0.7313, -0.0382]),
 tensor([-0.4170, -0.1202,  0.2281,  0.7306]),
 tensor([ 1.3281, -0.0493, -0.5024,  0.8513]),
 tensor([-0.0438, -0.7183, -1.8715,  1.1914]),
 tensor([ 0.3440, -1.9545, -0.2036,  2.1384]))

In [81]:
print(x, torch.add(x,20))

tensor([[ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384]]) tensor([[20.3947, 19.5830, 21.3281, 19.9562, 20.3440],
        [21.7530, 19.8798, 19.9507, 19.2817, 18.0455],
        [19.2687, 20.2281, 19.4976, 18.1285, 19.7964],
        [19.9618, 20.7306, 20.8513, 21.1914, 22.1384]])


In [82]:
print(x, torch.mul(x,2))

tensor([[ 0.3947, -0.4170,  1.3281, -0.0438,  0.3440],
        [ 1.7530, -0.1202, -0.0493, -0.7183, -1.9545],
        [-0.7313,  0.2281, -0.5024, -1.8715, -0.2036],
        [-0.0382,  0.7306,  0.8513,  1.1914,  2.1384]]) tensor([[ 0.7894, -0.8340,  2.6562, -0.0876,  0.6879],
        [ 3.5059, -0.2405, -0.0986, -1.4365, -3.9089],
        [-1.4626,  0.4561, -1.0048, -3.7430, -0.4071],
        [-0.0763,  1.4613,  1.7027,  2.3829,  4.2769]])


In [83]:
intercept = torch.randn(1)

In [84]:
x = torch.randn(2,2)

In [85]:
intercept,x

(tensor([0.3404]),
 tensor([[ 0.5183,  0.0186],
         [-0.4665,  0.5661]]))

In [86]:
beta = 0.7456
beta

0.7456

In [87]:
torch.mul(intercept, x)

tensor([[ 0.1764,  0.0063],
        [-0.1588,  0.1927]])

In [88]:
torch.mul(x, beta)

tensor([[ 0.3864,  0.0139],
        [-0.3478,  0.4221]])

In [90]:
torch.add(torch.mul(intercept,x), torch.mul(x,beta))

tensor([[ 0.5629,  0.0202],
        [-0.5066,  0.6148]])

In [91]:
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [92]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [93]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [94]:
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [95]:
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [96]:
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [99]:
torch.exp(x),torch.frac(torch.exp(x))

(tensor([[1.6791, 1.0188],
         [0.6272, 1.7614]]),
 tensor([[0.6791, 0.0188],
         [0.6272, 0.7614]]))

In [100]:
x

tensor([[ 0.5183,  0.0186],
        [-0.4665,  0.5661]])

In [102]:
torch.log(x)

tensor([[-0.6572, -3.9821],
        [    nan, -0.5690]])

In [103]:
torch.log(torch.pow(x,2))

tensor([[-1.3145, -7.9643],
        [-1.5249, -1.1379]])

In [104]:
x

tensor([[ 0.5183,  0.0186],
        [-0.4665,  0.5661]])

In [105]:
torch.sigmoid(x)

tensor([[0.6267, 0.5047],
        [0.3854, 0.6379]])

In [ ]:
torch.sqrt(x)